# A Battleship Launcher
# See license.txt for licensing details

#==========================================================
# Setup and defines
PYTHON=python
HERE=./

ifeq ($(OS),Windows_NT)
	PYTHON=C:\Python27\python.exe
	HERE=.\\
endif

#==========================================================
# Main entry point
main:
	$(PYTHON) $(HERE)BattleshipBots.py

#==========================================================
# Run!
run:
	$(PYTHON) $(HERE)BattleshipBots.py --debug LazyBot KRBot



